
//----------------------------------------------------
// The following code was generated by CUP v0.11b 20160615 (GIT 4ac7450)
//----------------------------------------------------

package com.proyecto1.analizadores;

/** CUP generated class containing symbol constants. */
public class sym {
  /* terminals */
  public static final int mayorQue = 33;
  public static final int conjunto = 16;
  public static final int orBooleana = 15;
  public static final int ampersand = 25;
  public static final int dosPuntos = 8;
  public static final int acentoCircunflejo = 38;
  public static final int corcheteC = 37;
  public static final int tilde = 18;
  public static final int corcheteA = 35;
  public static final int comillasDobles = 21;
  public static final int coma = 17;
  public static final int igual = 32;
  public static final int identificador = 5;
  public static final int guion = 29;
  public static final int numeral = 22;
  public static final int menorQue = 31;
  public static final int numero = 2;
  public static final int porcentaje = 24;
  public static final int caracteresEspeciales = 41;
  public static final int EOF = 0;
  public static final int mas = 12;
  public static final int error = 1;
  public static final int guionBajo = 39;
  public static final int punto = 13;
  public static final int letras = 3;
  public static final int llaveC = 10;
  public static final int puntoComa = 7;
  public static final int llaveA = 9;
  public static final int acentoGrave = 40;
  public static final int diagonalInversa = 36;
  public static final int arroba = 34;
  public static final int dolar = 23;
  public static final int parentesisC = 28;
  public static final int parentesisA = 27;
  public static final int asterisco = 11;
  public static final int comillaSimple = 26;
  public static final int valorIDConjunto = 19;
  public static final int admiracion = 20;
  public static final int interrogacion = 14;
  public static final int decimal = 4;
  public static final int diagonal = 30;
  public static final int cadena = 6;
  public static final String[] terminalNames = new String[] {
  "EOF",
  "error",
  "numero",
  "letras",
  "decimal",
  "identificador",
  "cadena",
  "puntoComa",
  "dosPuntos",
  "llaveA",
  "llaveC",
  "asterisco",
  "mas",
  "punto",
  "interrogacion",
  "orBooleana",
  "conjunto",
  "coma",
  "tilde",
  "valorIDConjunto",
  "admiracion",
  "comillasDobles",
  "numeral",
  "dolar",
  "porcentaje",
  "ampersand",
  "comillaSimple",
  "parentesisA",
  "parentesisC",
  "guion",
  "diagonal",
  "menorQue",
  "igual",
  "mayorQue",
  "arroba",
  "corcheteA",
  "diagonalInversa",
  "corcheteC",
  "acentoCircunflejo",
  "guionBajo",
  "acentoGrave",
  "caracteresEspeciales"
  };
}

