
//----------------------------------------------------
// The following code was generated by CUP v0.11b 20160615 (GIT 4ac7450)
//----------------------------------------------------

package com.proyecto1.analizadores;

/** CUP generated class containing symbol constants. */
public class sym {
  /* terminals */
  public static final int conjunto = 20;
  public static final int decimal = 5;
  public static final int coma = 21;
  public static final int porcentajes = 12;
  public static final int numero = 3;
  public static final int comillaSimple = 24;
  public static final int comillasDobles = 23;
  public static final int caracter = 6;
  public static final int letras = 4;
  public static final int saltoLinea = 25;
  public static final int guion = 10;
  public static final int llaveC = 9;
  public static final int EOF = 0;
  public static final int llaveA = 8;
  public static final int error = 1;
  public static final int tilde = 22;
  public static final int asterisco = 17;
  public static final int interrogacion = 19;
  public static final int mas = 18;
  public static final int dosPuntos = 14;
  public static final int puntoComa = 13;
  public static final int guionBajo = 7;
  public static final int orBooleana = 16;
  public static final int concatenacion = 15;
  public static final int identificador = 2;
  public static final int mayorQue = 11;
  public static final String[] terminalNames = new String[] {
  "EOF",
  "error",
  "identificador",
  "numero",
  "letras",
  "decimal",
  "caracter",
  "guionBajo",
  "llaveA",
  "llaveC",
  "guion",
  "mayorQue",
  "porcentajes",
  "puntoComa",
  "dosPuntos",
  "concatenacion",
  "orBooleana",
  "asterisco",
  "mas",
  "interrogacion",
  "conjunto",
  "coma",
  "tilde",
  "comillasDobles",
  "comillaSimple",
  "saltoLinea"
  };
}

