/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package com.proyecto1.interfaz;
import com.proyecto1.analizadores.*;
import com.proyecto1.archivos.Lectura;
import com.proyecto1.estructuras.Instancias;
import com.proyecto1.estructuras.abb.ABB;
//import com.proyecto1.estructuras.pojos.TError;
import com.proyecto1.estructuras.arbol.*;
import com.proyecto1.estructuras.avl.ArbolAVL;
import com.proyecto1.estructuras.pojos.*;
import java.io.File;
import java.io.IOException;
import java.io.StringReader;
import java.util.Iterator;
import java.util.Stack;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.JFileChooser;
import javax.swing.JOptionPane;
import javax.swing.filechooser.FileNameExtensionFilter;

/**
 *
 * @author Gonzalo
 */
public class Pantalla_principal extends javax.swing.JFrame {

    /**
     * Creates new form Pantalla_principal
     */
    
    public static String list_of_names="";
    public Pantalla_principal() {
        Instancias.arbol_binario_expresiones = new ArbolAVL();
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jScrollPane1 = new javax.swing.JScrollPane();
        txtEntrada = new javax.swing.JTextArea();
        btnCompilar = new javax.swing.JButton();
        jScrollPane2 = new javax.swing.JScrollPane();
        txtSalida = new javax.swing.JTextArea();
        labelTXTSalida = new javax.swing.JLabel();
        labelTXTEntrada1 = new javax.swing.JLabel();
        btnGenerarAutomata = new javax.swing.JButton();
        jScrollPane3 = new javax.swing.JScrollPane();
        jtreeOpciones = new javax.swing.JTree();
        canvas1 = new java.awt.Canvas();
        jComboBox1 = new javax.swing.JComboBox<>();
        jMenuBar1 = new javax.swing.JMenuBar();
        menuArchivo = new javax.swing.JMenu();
        menuAbrir = new javax.swing.JMenuItem();
        menuGuardar = new javax.swing.JMenuItem();
        menuGuardarComo = new javax.swing.JMenuItem();
        menuGenerarJSON = new javax.swing.JMenuItem();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        txtEntrada.setColumns(20);
        txtEntrada.setRows(5);
        jScrollPane1.setViewportView(txtEntrada);

        btnCompilar.setText("Analizar entrada");
        btnCompilar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnCompilarActionPerformed(evt);
            }
        });

        txtSalida.setColumns(20);
        txtSalida.setRows(5);
        txtSalida.setEnabled(false);
        jScrollPane2.setViewportView(txtSalida);

        labelTXTSalida.setText("Salida");

        labelTXTEntrada1.setText("Archivo de entrada");

        btnGenerarAutomata.setText("Generar automata");
        btnGenerarAutomata.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnGenerarAutomataActionPerformed(evt);
            }
        });

        jScrollPane3.setViewportView(jtreeOpciones);

        jComboBox1.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Item 1", "Item 2", "Item 3", "Item 4" }));

        menuArchivo.setText("Archivo");

        menuAbrir.setText("Abrir");
        menuAbrir.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                menuAbrirActionPerformed(evt);
            }
        });
        menuArchivo.add(menuAbrir);

        menuGuardar.setText("Guardar");
        menuGuardar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                menuGuardarActionPerformed(evt);
            }
        });
        menuArchivo.add(menuGuardar);

        menuGuardarComo.setText("Guardar como");
        menuArchivo.add(menuGuardarComo);

        menuGenerarJSON.setText("Generar JSON");
        menuGenerarJSON.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                menuGenerarJSONActionPerformed(evt);
            }
        });
        menuArchivo.add(menuGenerarJSON);

        jMenuBar1.add(menuArchivo);

        setJMenuBar(jMenuBar1);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(50, 50, 50)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 344, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(labelTXTEntrada1)
                            .addComponent(labelTXTSalida)))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(87, 87, 87)
                        .addComponent(btnGenerarAutomata)
                        .addGap(51, 51, 51)
                        .addComponent(btnCompilar))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(27, 27, 27)
                        .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 405, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addGap(26, 26, 26)
                .addComponent(jScrollPane3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(38, 38, 38)
                        .addComponent(canvas1, javax.swing.GroupLayout.PREFERRED_SIZE, 302, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(89, 89, 89)
                        .addComponent(jComboBox1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(47, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(20, 20, 20)
                .addComponent(labelTXTEntrada1)
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jScrollPane1)
                        .addGap(9, 9, 9)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(btnCompilar)
                            .addComponent(btnGenerarAutomata))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(labelTXTSalida)
                        .addGap(18, 18, 18)
                        .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 118, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(21, 21, 21))
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jScrollPane3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGroup(layout.createSequentialGroup()
                                .addGap(18, 18, 18)
                                .addComponent(jComboBox1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(48, 48, 48)
                                .addComponent(canvas1, javax.swing.GroupLayout.PREFERRED_SIZE, 233, javax.swing.GroupLayout.PREFERRED_SIZE)))
                        .addContainerGap(47, Short.MAX_VALUE))))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnCompilarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnCompilarActionPerformed
        list_of_names = "";
        txtSalida.setText("");
        Instancias.limpiar();
        
        String cadenaEntrada = txtEntrada.getText();
        Parser sintactico;
        Lexico lexico = new Lexico(new StringReader(cadenaEntrada));
        sintactico = new Parser(lexico);
        Lexico.TablaEL.clear();
        Parser.TablaES.clear();
        try {
            sintactico.parse();
            txtSalida.setText(Parser.resultado);
            txtSalida.updateUI();
//            System.out.println("\nNODOS EN AST");
//            Parser.raiz.mostrarNodo();
            // Mostrando errores sintacticos
            System.out.println("\nErroes sintacticos:");
            if(Parser.TablaES.size() > 0){
                Parser.TablaES.forEach(erroresSintacticos -> {
                    erroresSintacticos.mostrar();
                });
            }
            // Mostrando errores lexicos
            System.out.println("\nErroes lexicos:");
            if(Lexico.TablaEL.size() > 0){
                Lexico.TablaEL.forEach(erroresLexicos -> {
                    erroresLexicos.mostrar();
                });
            }
            
            // Mostrando listas de conjuntos
            System.out.println("\nLista de conjuntos:");
            String reconocido = "";
            for (Conjunto conjuntoTemporal : Instancias.listaConjuntos) {
                conjuntoTemporal.mostrar();
                reconocido += "\nCONJUNTOS:\n";
                reconocido += conjuntoTemporal.mostrarStr();
            }
            // Mostrando listas de expresiones
            System.out.println("\nLista de expresiones:");
            for (Expresion expresionTemporal : Instancias.listaExpresiones) {
                expresionTemporal.mostrar();
                reconocido += "\nEXPRESIONES:\n";
                reconocido += expresionTemporal.mostrarStr();
            }
            // Mostrando listas de lexemas
            System.out.println("\nLista de lexemas:");
            for (Lexema lexemaTemporal : Instancias.listaLexemas) {
                lexemaTemporal.mostrar();
                reconocido += "\nLEXEMAS:\n";
                reconocido += lexemaTemporal.mostrarStr();
            }
            txtSalida.setText(reconocido);
            txtSalida.updateUI();
            
            // STACK EXP
//            for (Iterator i = Instancias.listaExpresionesPila.iterator(); i.hasNext();) {
//            for (Object a : Instancias.listaExpresionesPila) {
//                System.out.println("\nPila de expresiones: ");
//                for (ValorExpresiones pilaValExpTemp : (Stack<ValorExpresiones>) a ) {
//                    pilaValExpTemp.mostrar();
//                }
//            }
            
            System.out.println("\nArbol: ");
//            
//             if(!Instancias.arbol_binario_expresiones.esVacio()){
//                    Instancias.arbol_binario_expresiones.inorder();
//                    try {
//                        Instancias.arbol_binario_expresiones.graficar("grafo");
//                        JOptionPane.showMessageDialog(null, "Se grafico el arbol binario de busqueda, de capas.", 
//                        "Informacion", JOptionPane.INFORMATION_MESSAGE);
//                    } catch (IOException ex) {
//                        Logger.getLogger(Pantalla_principal.class.getName()).log(Level.SEVERE, null, ex);
//                    } catch (InterruptedException ex) {
//                        Logger.getLogger(Pantalla_principal.class.getName()).log(Level.SEVERE, null, ex);
//                    }
//                }else{
//                    JOptionPane.showMessageDialog(null, "No se han cargado las capas", 
//                    "Atencion", JOptionPane.WARNING_MESSAGE);
//                }
//            Stack<ValorExpresiones> a = (Stack<ValorExpresiones>) Instancias.listaExpresionesPila.get(0);
//            System.out.println("Tam lista pilas: " + Instancias.listaExpresionesPila.size());
//            System.out.println("Tam pila: " + a.size());
//            for (ValorExpresiones pilaValExpTemp : a ) {
//                pilaValExpTemp.mostrar();
//            }
        } catch (Exception e) {
        }
    }//GEN-LAST:event_btnCompilarActionPerformed

    private void menuGuardarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_menuGuardarActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_menuGuardarActionPerformed

    private void menuGenerarJSONActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_menuGenerarJSONActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_menuGenerarJSONActionPerformed

    private void btnGenerarAutomataActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnGenerarAutomataActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_btnGenerarAutomataActionPerformed
// File Chooser
    String directorio_archivos = "C:\\Users\\Gonzalo\\Desktop\\Entrada";
    final JFileChooser fc = new JFileChooser(directorio_archivos);
    private void menuAbrirActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_menuAbrirActionPerformed
        // TODO add your handling code here:
//        if(avl_usuarios.esVacio()){
            fc.setFileFilter(new FileNameExtensionFilter("Archivos de entrada", "olc", "olc"));
            int valor = fc.showOpenDialog(null);
            if(valor == JFileChooser.APPROVE_OPTION){
                File archivo = fc.getSelectedFile();
                String ruta = archivo.getAbsolutePath();
    //            System.out.println(ruta);
                try {
                    txtEntrada.setText(Lectura.leer(ruta));
                    JOptionPane.showMessageDialog(null, "Se ha terminado de leer el archivo de entrada.", 
                            "Informacion", JOptionPane.INFORMATION_MESSAGE);
                } catch (IOException ex) {
                    Logger.getLogger(Pantalla_principal.class.getName()).log(Level.SEVERE, null, ex);
                } catch (InterruptedException ex) {
                    Logger.getLogger(Pantalla_principal.class.getName()).log(Level.SEVERE, null, ex);
                }
            }
//        }else{
//            JOptionPane.showMessageDialog(null, "Ya se han cargado los usuarios", 
//            "Atencion", JOptionPane.WARNING_MESSAGE);
//        }
    }//GEN-LAST:event_menuAbrirActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Pantalla_principal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Pantalla_principal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Pantalla_principal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Pantalla_principal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Pantalla_principal().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnCompilar;
    private javax.swing.JButton btnGenerarAutomata;
    private java.awt.Canvas canvas1;
    private javax.swing.JComboBox<String> jComboBox1;
    private javax.swing.JMenuBar jMenuBar1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JScrollPane jScrollPane3;
    private javax.swing.JTree jtreeOpciones;
    private javax.swing.JLabel labelTXTEntrada1;
    private javax.swing.JLabel labelTXTSalida;
    private javax.swing.JMenuItem menuAbrir;
    private javax.swing.JMenu menuArchivo;
    private javax.swing.JMenuItem menuGenerarJSON;
    private javax.swing.JMenuItem menuGuardar;
    private javax.swing.JMenuItem menuGuardarComo;
    private javax.swing.JTextArea txtEntrada;
    private javax.swing.JTextArea txtSalida;
    // End of variables declaration//GEN-END:variables
}
